### ISSUE TITLE
Docker on macOS arm64

### ISSUE THREAD

**Issue by jgoodall** [kermitt2/grobid#1089]
I cannot run the full docker image on an arm64 Mac (environment details below). I can run `docker run --init -p 8070:8070 lfoppiano/grobid:0.8.0` and that works, but if I try the full image, it immediately quits (same result with tag `0.8.1-SNAPSHOT`):

```
docker run --init -p 8070:8070 grobid/grobid:0.8.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
WARN  [2024-03-05 16:57:33,076] org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable: HV000254: Missing parameter metadata for ResponseMeteredLevel(String, int), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
```

I am using Orbstack, and if I uncheck `Use Rosetta to run Intel code`, instead of the `AVX instructions` error, I get `SSE4.1 instructions`. My understanding based on the docs and the issues is that the deep learning image _should_ work on CPUs on macOS using emulation, but I dont see instructions for doing that. I see a reference to `libwapiti.dylib`, but not how to get that or what to do with it. 

Would it be possible to provide detailed instructions for somehow getting the `grobid/grobid` docker image working on a mac?

## Related issues:

* #928 - this is specific to linux on arm64, and is still open
* #937 - this has a merged PR, which makes it seem like it should work
* #1002 - this makes it seem like grobid can run on macOS outside of docker

## Environment details

macOS is 14.3.1 with an M2 chip. OrbStack 1.4.3.

Docker Info:

```
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:35 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by lfoppiano** [comment]
Dear @jgoodall, 
   thank you for reporting this issue. 

Indeed we can run Grobid on M1 (and, I suppose M2, but I did not test it) outside docker (#935, #1002). 
However, for docker, the situation is a bit different. 
There is a docker image that should work fine on ARM: `lfoppiano/docker:0.8.0-arm`, however, given the lack of time, there is certainly room for improvement. 
This image is available for versions 0.7.3 and 0.8.0, however, they are not documented yet because they were not very stable at the time we tested (#1014). 

The use case is a bit weak for me, as I run Grobid on my Mac only for development, and I prefer to run the server on a Linux machine for serious processing. 

Maybe give it a try to the 0.8.0-arm and let me know. We can try to support more the arm architecture meanwhile.

**Comment by jgoodall** [comment]
To be clear, the `lfoppiano/grobid` image works fine on M2 chip. It is the `grobid/grobid` that is not working.

That said - since you already have the `arm` image for the `lfoppiano/grobid` build, you can create a single multi-arch build of the two images you have with a single manifest so that users would automatically get the right image for their architecture. I tested that and pushed to my namespace, but you would obviously want to do this to the `lfoppiano` namespace. (I am assuming you build the `arm` image using `--build-arg ARCH=arm64v8`, but I am not seeing where in the repo that is being built.) Here is a proof-of-concept of having a single multi-arch build for the CRF image:

```
VERS=0.8.0

docker pull lfoppiano/grobid:$VERS
docker tag lfoppiano/grobid:$VERS jgoodall/grobid-crf:$VERS-amd64
docker push jgoodall/grobid-crf:$VERS-amd64

docker pull lfoppiano/grobid:$VERS-arm
docker tag lfoppiano/grobid:$VERS-arm jgoodall/grobid-crf:$VERS-arm64v8
docker push jgoodall/grobid-crf:$VERS-arm64v8

docker manifest create jgoodall/grobid-crf:$VERS \
--amend jgoodall/grobid-crf:$VERS-amd64 \
--amend jgoodall/grobid-crf:$VERS-arm64v8
docker manifest push jgoodall/grobid-crf:$VERS
```

I imagine that will be trickier since the `openjdk` runtime image you use for the CRF already supports arm, but the `tensorflow` image you use for the full docker image does not. I would be happy to help, but I am not a Java person, so if someone can create an appropriate arm64 image for `grobid/grobid`, I can help figure out the docker manifest commands.

We also only run on Mac for development and Linux for production, and would like to be able to use the same image (`grobid/grobid`) on both. My workaround right now is to use the `lfoppiano/grobid` on mac and the `grobid/grobid` on Linux, but would much prefer to use the same for both environments. I just cannot figure out how to do that, so any guidance would be great.

**Comment by lfoppiano** [comment]
Thanks. 
I'm sorry, I'm a bit short on time to dedicate to grobid at the moment, so I don't know when I will be able to work on this. 

Would you be able to submit a PR for this change?

**Comment by rgranit** [comment]
Same issue here.. would be great to have a single image solution for mac and linux

**Comment by lfoppiano** [comment]
Please check #1165, there is an double-arch image. I would appreciate if you could give it a try, with particular attention to the issue with the pdfalto processes.

**Comment by heijligers** [comment]
Hi there. Looking for a working docker macos m1 image and intructions. thank you

**Comment by lfoppiano** [comment]
I believe that the latest image `lfoppiano/grobid:latest-crf-multi-arch` should work 

(sorry for cross commenting, I'm trying to get everybody interested to receive the message)

**Comment by jgoodall** [comment]
@lfoppiano - that image is working for me with no issues on arm64 (mac)

**Comment by jgoodall** [comment]
We have been using this image for a while now, but i would like to see an actual tagged version for this variant.  I am actually not sure what version i am using now since that is dependent on when i pulled `latest-crf-multi-arch`. 

Could you tag this the same way you tag the `crf` image, like `0.8.2.1-crf`, instead of just using `latest`.  Or just merge the `crf-multi-arch` image into the `crf` image?

**Comment by lfoppiano** [comment]
Dear @jgoodall the multi arch version will go in the next release which is due shortly. Since we have a new pdfalto version that also supports ARM Linux, this is taking more time.

**Comment by jgoodall** [comment]
Great news - let me know if you want help testing.

**Comment by jgoodall** [comment]
@lfoppiano -- we have been using the `crf-multi-arch` image for a while now, but at this point the JRE has gotten outdated and contains multiple vulnerabilities. Would it be possible to update the JDK/JRE images from `eclipse-temurin:21-jdk` and `eclipse-temurin:21-jre` to `25` tags (`25-jre` and `25-jdk`) to bring address these? Or even just the minor release update `21.0.9_10-jre` to address the high vulnerability?

**Comment by jgoodall** [comment]
I updated the `eclipse-temurin` java version to `21.0.9_10` in a fork for `multi-arch-docker-image` branch, let me know if you want me to create a PR.

**Comment by lfoppiano** [comment]
@jgoodall yes please! Thanks a lot! 👍

**Comment by jgoodall** [comment]
https://github.com/grobidOrg/grobid/pull/1364

Updated the version again this morning as it was released overnight. Let me know if this works - if so I will keep that branch up to date.

**Comment by lfoppiano** [comment]
I've merged the long standing branch into master.

**Comment by lfoppiano** [comment]
@jgoodall I've released the RC1 on docker: https://hub.docker.com/r/lfoppiano/grobid/tags?name=0.9.0 

could you try the ARM version and let me know if everything works fine? Also I've updated all libraries, but feel free to point out any security problem

**Comment by jgoodall** [comment]
@lfoppiano -- i tried the CRF image in our kubernetes workload and worked great for a few smaller files. Is it much faster?
For a 130MB PDF the grobid server crashed in our workload. I cant tell why, but assuming OOM?

I have the workload resource request limit as:

```
        resources:
          requests:
            cpu: "1"
            memory: 4.5Gi
          limits:
            cpu: "1"
            memory: 4.5Gi
```

and in the grobid config (maybe this changed in new version? this is from older version). and if i remember right, I could not just set the config I wanted to change (memory and resource related) - I had to include the whole thing. I think the only thing relevant is `pdf.pdfalto.memoryLimitMb: 4096`, but below is the whole thing. I dont know if you have any guidance about memory allocation needed in terms of text extraction for large PDFs.

```
# this is the configuration file for the GROBID instance

grobid:
  # where all the Grobid resources are stored (models, lexicon, native libraries, etc.), normally no need to change
  grobidHome: "grobid-home"

  # path relative to the grobid-home path (e.g. tmp for grobid-home/tmp) or absolute path (/tmp)
  temp: "/tmp"

  # normally nothing to change here, path relative to the grobid-home path (e.g. grobid-home/lib)
  nativelibrary: "lib"

  pdf:
    pdfalto:
      # path relative to the grobid-home path (e.g. grobid-home/pdfalto), you don't want to change this normally
      path: "pdfalto"
      # security for PDF parsing
      memoryLimitMb: 4096
      timeoutSec: 320

    # security relative to the PDF parsing result
    blocksMax: 200000
    tokensMax: 1500000

  consolidation:
    # define the bibliographical data consolidation service to be used, either "crossref" for CrossRef REST API or 
    # "glutton" for https://github.com/kermitt2/biblio-glutton
    service: "crossref"
    #service: "glutton"
    glutton:
      #url: "https://cloud.science-miner.com/glutton"
      url: "http://localhost:8080"
      timeoutSec: 60
    crossref:
      mailto: # NOTE! To use the Crossref web API, you need normally to use it politely

      # and to indicate an email address here, e.g. mailto: "toto@titi.tutu"
      token: # to use Crossref metadata plus service (available by subscription)

      #token: "yourmysteriouscrossrefmetadataplusauthorizationtokentobeputhere"
      timeoutSec: 60
      # Timeout for CrossRef API calls (in seconds) - USE with CARE!
  proxy:
    # proxy to be used when doing external call to the consolidation service
    host:
    port:

      # CORS configuration for the GROBID web API service
  corsAllowedOrigins: "*"
  corsAllowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
  corsAllowedHeaders: "X-Requested-With,Content-Type,Accept,Origin"

  # the actual implementation for language recognition to be used
  languageDetectorFactory: "org.grobid.core.lang.impl.CybozuLanguageDetectorFactory"

  # the actual implementation for optional sentence segmentation to be used (PragmaticSegmenter or OpenNLP)
  #sentenceDetectorFactory: "org.grobid.core.lang.impl.PragmaticSentenceDetectorFactory"
  sentenceDetectorFactory: "org.grobid.core.lang.impl.OpenNLPSentenceDetectorFactory"

  # maximum concurrency allowed to GROBID server for processing parallel requests - change it according to your CPU/GPU capacities
  # for a production server running only GROBID, set the value slightly above the available number of threads of the server
  # to get the best performance and security
  concurrency: 4
  # when the pool is full, for queries waiting for the availability of a Grobid engine, this is the maximum time wait to try 
  # to get an engine (in seconds) - normally never change it
  poolMaxWait: 1

  delft:
    # DeLFT global parameters
    # delft installation path if Deep Learning architectures are used to implement one of the sequence labeling model, 
    # embeddings are usually compiled as lmdb under delft/data (this parameter is ignored if only featured-engineered CRF are used)
    install: "../delft"
    pythonVirtualEnv:


  wapiti:
    # Wapiti global parameters
    # number of threads for training the wapiti models (0 to use all available processors)
    nbThreads: 0

  models:
  # we configure here how each sequence labeling model should be implemented
  # for feature-engineered CRF, use "wapiti" and possible training parameters are window, epsilon and nbMaxIterations
  # for Deep Learning, use "delft" and select the target DL architecture (see DeLFT library), the training 
  # parameters then depends on this selected DL architecture 

  - name: "segmentation"
    # at this time, must always be CRF wapiti, the input sequence size is too large for a Deep Learning implementation
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 1e-7
      window: 50
      nbMaxIterations: 2000
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"
      useELMo: false
      runtime:
        # parameters used at runtime/prediction
        max_sequence_length: 3000
        batch_size: 1
      training:
        # parameters used for training
        max_sequence_length: 3000
        batch_size: 10

  - name: "segmentation-article-light"
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 1e-7
      window: 50
      nbMaxIterations: 2000

  - name: "segmentation-article-light-ref"
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 1e-7
      window: 50
      nbMaxIterations: 2000

  - name: "segmentation-sdo-ietf"
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 1e-7
      window: 50
      nbMaxIterations: 2000

  - name: "fulltext"
    # at this time, must always be CRF wapiti, the input sequence size is too large for a Deep Learning implementation
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.0001
      window: 20
      nbMaxIterations: 1500

  - name: "header"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only  
      epsilon: 0.000001
      window: 30
      nbMaxIterations: 1500
    delft:
      # deep learning parameters
      architecture: "BidLSTM_ChainCRF_FEATURES"
      #transformer: "allenai/scibert_scivocab_cased"
      useELMo: false
      runtime:
        # parameters used at runtime/prediction
        #max_sequence_length: 510
        max_sequence_length: 3000
        batch_size: 1
      training:
        # parameters used for training
        #max_sequence_length: 510
        #batch_size: 6
        max_sequence_length: 3000
        batch_size: 9

  - name: "header-article-light"
    engine: "wapiti"
    #      engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.000001
      window: 30
      nbMaxIterations: 1500
    delft:
      architecture: "BidLSTM_ChainCRF_FEATURES"
      useELMo: false

  - name: "header-article-light-ref"
    engine: "wapiti"
    #      engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.000001
      window: 30
      nbMaxIterations: 1500
    delft:
      architecture: "BidLSTM_ChainCRF_FEATURES"
      useELMo: false

  - name: "header-sdo-ietf"
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.000001
      window: 30
      nbMaxIterations: 1500

  - name: "reference-segmenter"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 20
    delft:
      # deep learning parameters
      architecture: "BidLSTM_ChainCRF_FEATURES"
      useELMo: false
      runtime:
        # parameters used at runtime/prediction (for this model, use same max_sequence_length as training)
        max_sequence_length: 3000
        batch_size: 2
      training:
        # parameters used for training
        max_sequence_length: 3000
        batch_size: 10

  - name: "name-header"
    engine: "wapiti"
    #engine: "delft"
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"

  - name: "name-citation"
    engine: "wapiti"
    #engine: "delft"
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"

  - name: "date"
    engine: "wapiti"
    #engine: "delft"
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"

  - name: "figure"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 20
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF"

  - name: "table"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 20
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF"

  - name: "affiliation-address"
    engine: "wapiti"
    #engine: "delft"
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"

  - name: "citation"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 50
      nbMaxIterations: 3000
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"
      #architecture: "BERT_CRF"
      #transformer: "michiyasunaga/LinkBERT-base"
      useELMo: false
      runtime:
        # parameters used at runtime/prediction
        max_sequence_length: 500
        batch_size: 30
      training:
        # parameters used for training
        max_sequence_length: 500
        batch_size: 50

  - name: "patent-citation"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.0001
      window: 20
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"
      #architecture: "BERT_CRF"
      runtime:
        # parameters used at runtime/prediction
        max_sequence_length: 800
        batch_size: 20
      training:
        # parameters used for training
        max_sequence_length: 1000
        batch_size: 40

  - name: "funding-acknowledgement"
    engine: "wapiti"
    #engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 50
      nbMaxIterations: 2000
    delft:
      # deep learning parameters
      architecture: "BidLSTM_CRF_FEATURES"
      #architecture: "BERT_CRF"
      #transformer: "michiyasunaga/LinkBERT-base"
      useELMo: false
      runtime:
        # parameters used at runtime/prediction
        max_sequence_length: 800
        batch_size: 20
      training:
        # parameters used for training
        max_sequence_length: 500
        batch_size: 40

  - name: "copyright"
    # at this time, we only have a DeLFT implementation, 
    # use "wapiti" if the deep learning library JNI is not available and model will then be ignored
    #engine: "delft"
    engine: "wapiti"
    delft:
      # deep learning parameters
      architecture: "gru"
      #architecture: "bert"
      #transformer: "allenai/scibert_scivocab_cased"

  - name: "license"
    # at this time, for being active, it must be DeLFT, no other implementation is available
    # use "wapiti" if the deep learning library JNI is not available and model will then be ignored
    #engine: "delft"
    engine: "wapiti"
    delft:
      # deep learning parameters
      architecture: "gru"
      #architecture: "bert"
      #transformer: "allenai/scibert_scivocab_cased"

      # for **service only**: how to load the models, 
      # false -> models are loaded when needed, avoiding putting in memory useless models (only in case of CRF) but slow down 
      #          significantly the service at first call
      # true -> all the models are loaded into memory at the server startup (default), slow the start of the services 
      #         and models not used will take some more memory (only in case of CRF), but server is immediatly warm and ready
  modelPreload: true

server:
  type: custom
  applicationConnectors:
  - type: http
    port: 3000
  adminConnectors:
  - type: http
    port: 3001
  registerDefaultExceptionMappers: false
  # change the following for having all http requests logged
  requestLog:
    appenders: []

# these logging settings apply to the Grobid service usage mode
logging:
  level: INFO
  loggers:
    org.apache.pdfbox.pdmodel.font.PDSimpleFont: "OFF"
    org.glassfish.jersey.internal: "OFF"
    com.squarespace.jersey2.guice.JerseyGuiceUtils: "OFF"
  appenders:
  - type: console
    threshold: INFO
    timeZone: UTC
    # uncomment to have the logs in json format
    #layout:
    #  type: json
```

**Comment by lfoppiano** [comment]
@jgoodall so you used the ARM image, right? Could you share the PDF that crashed the server? Do you have any log error?

**Comment by jgoodall** [comment]
Sorry, yes - it was the arm image:

```
docker inspect lfoppiano/grobid:0.9.0-RC1-crf | grep Arch
        "Architecture": "arm64",
```

Unfortunately - I cannot share that PDF - do you have a large one you want me to test?

There was nothing in the logs, this is what it logged for the successful files, and then when container crashed I didnt see anything:

```
INFO  [2026-03-06 15:50:21,395] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@8ac12e6{Application context,/,null,AVAILABLE}
INFO  [2026-03-06 15:50:21,408] io.dropwizard.core.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2026-03-06 15:50:21,410] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@baa227e{Admin context,/,null,AVAILABLE}
INFO  [2026-03-06 15:50:21,415] org.eclipse.jetty.server.AbstractConnector: Started application@66223d94{HTTP/1.1, (http/1.1)}{0.0.0.0:3000}
INFO  [2026-03-06 15:50:21,415] org.eclipse.jetty.server.AbstractConnector: Started admin@2bc7db89{HTTP/1.1, (http/1.1)}{0.0.0.0:3001}
INFO  [2026-03-06 15:50:21,416] org.eclipse.jetty.server.Server: Started Server@75b38c36{STARTING}[11.0.26,sto=30000] @14569ms
INFO  [2026-03-06 15:51:11,820] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/4
INFO  [2026-03-06 15:51:24,238] org.grobid.core.engines.FullTextParser: Number of tables badly formatted or incomplete we identified: 4
INFO  [2026-03-06 15:51:34,928] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/4
INFO  [2026-03-06 15:52:13,398] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/4
INFO  [2026-03-06 15:52:15,008] org.grobid.core.engines.FullTextParser: Number of tables badly formatted or incomplete we identified: 5
INFO  [2026-03-06 15:52:15,037] org.grobid.core.engines.FullTextParser: Number of tables badly formatted or incomplete we identified in Annex: 5
INFO  [2026-03-06 15:52:37,937] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/4
```

**Comment by lfoppiano** [comment]
OK. Could you try the PDF on an older docker image, and also on https://huggingface.co/spaces/lfoppiano/grobid-dimensions ? I would like to know whether this is just one single PDF messing up or if this is a regression somehow.

**Comment by lfoppiano** [comment]
> I have the workload resource request limit as:

```
        resources:
          requests:
            cpu: "1"
            memory: 4.5Gi
          limits:
            cpu: "1"
            memory: 4.5Gi
```

has this been always the same? Usually I would recommend to allocate the `number of cpu` = `nb of concurrency -1`, so in your case I would set it to 3, especially if you have to process such big PDF files.
